version: '3'

services:
  app:
    build:
      context: .
      dockerfile: "build/Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"

  mongodb:
    image: "mongo:6.0.5"
    ports:
      - "27017:27017"
