all:
	sudo docker compose up -d --build

ls:
	sudo docker container ls -a

logs:
	sudo docker container logs -f tgbot-app-1

stop:
	sudo docker container stop tgbot-app-1
	sudo docker container stop tgbot-mongodb-1
